name: Merge Release Artifacts

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
      

jobs:
  merge-artifacts:
    if: ${{ github.event.pull_request.merged == true }}  # Only run if the PR was merged, not just closed
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Make the script executable
      - name: Make merge-release-artifacts.sh executable
        run: chmod +x scripts/file_merger.sh

      # Run the merge-release-artifacts.sh script using bash
      - name: Run merge release artifacts script
        run: bash scripts/file_merger.sh
        env:
          pr_from_branch: ${{ github.head_ref }}
          pr_to_branch: ${{ github.base_ref }}
          WORKSPACE: ${{ github.workspace }}
