version: '1.0'

jobs:
  update_release_artifacts:
    description: "Script to merge release artifacts from feature to sprint directory"
    triggers:
      - type: git
        branch: "${pr_from_branch}"
    steps:
      - name: Determine Git Branch
        script: |
          if [ "${pr_from_branch}" == "origin/master" ]; then
            git_branch_local=$(echo "${pr_from_branch}" | sed -e "s|origin/||g")
          else
            git_branch_local=$(echo "${pr_from_branch}" | sed -e "s|feature/||g")
          fi
          
          branch_type=$(echo "${pr_to_branch}" | rev | cut -f 2 -d"/" | rev)
          
          if [[ "${pr_to_branch}" != "feature/develop" && "${branch_type}" != "release" && "${pr_to_branch}" != "origin/master" ]]; then
            echo "Update Release Artifacts: Started"
            git_branch_target=$(echo "${pr_to_branch}" | rev | cut -f 1 -d"/" | rev)
            
            SOURCE_DIR="${WORKSPACE}/release/${git_branch_local}"
            TARGET_DIR="${WORKSPACE}/release/${git_branch_target}"
            
            if [[ ! -d "${TARGET_DIR}" ]]; then
              echo "Creating directory ${TARGET_DIR}..."
              mkdir -p "${TARGET_DIR}"
            else
              echo "Release folder ${TARGET_DIR} exists..."
            fi
            
            for sourceFile in ${SOURCE_DIR}/*; do
              file="$(basename "${sourceFile}")"
              targetFile="${TARGET_DIR}/${file}"
              
              if [[ ! -f "${TARGET_DIR}/${file}" ]]; then
                echo "# release/${git_branch_target}" >> "${targetFile}"
              fi
              
              echo "${targetFile}"
              (cat "${sourceFile}"; echo) >> "${targetFile}"
              copyFile="copy_${file}"
              cat "${targetFile}" > "${copyFile}"
              awk '!seen[$0]++' "${sourceFile}" "${copyFile}" | sort | egrep -v "^#|^$|^ " > "${targetFile}"
              rm -f "${copyFile}"
            done
            echo "Update Release Artifacts: Completed"
          fi
    commit:
      description: "Navigate to project workspace and commit the updated release artifacts"
      action: "commit"
      message: "Committing updated release artifacts"
      # Note: Commit action will depend on your CI/CD tool's capabilities
