name: Validate
on: 
  pull_request:
    branches:
      - develop
    paths: 
      - 'force-app/**'
jobs:
 validate:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4.1.7
   - name: Validate
     uses: ./.github/actions


     with:
      SFDX_AUTH_URL: ${{secrets.SFDX_AUTH_URL}}
      DRY_RUN: true
      TEST_LEVEL: NoTestRun
